#!/bin/bash
set -e

s3d-push

module=$(git remote get-url ssh | sed 's/.*\///' | sed 's/\.git//')
v=$(s3d-flow-json | jq -r .latest)

s3d-flow-down() {
  sed -i "s/$module?ref=.*\"/$module?ref=$v\"/" *.tf
  s3d-flow
}

(cd ../aws-site && s3d-flow-down)
